# Generated by Django 2.1.15 on 2020-03-07 14:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MedicineHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MedicinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('latin_name', models.TextField(default='', verbose_name='拉丁名')),
                ('eng_name', models.TextField(default='', verbose_name='英文名')),
                ('category', models.TextField(default='', verbose_name='类别')),
                ('origin', wagtail.core.fields.RichTextField(default='', verbose_name='来源')),
                ('production_region', wagtail.core.fields.RichTextField(default='', verbose_name='产地')),
                ('features', wagtail.core.fields.RichTextField(default='', verbose_name='性状')),
                ('quality_requirements', wagtail.core.fields.RichTextField(default='', verbose_name='品质')),
                ('properties', wagtail.core.fields.RichTextField(default='', verbose_name='性味')),
                ('functions', wagtail.core.fields.RichTextField(default='', verbose_name='功效')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrescriptionComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('medicine_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.MedicinePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrescriptionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('eng_name', models.TextField(default='', verbose_name='英文名')),
                ('classification', models.TextField(default='', verbose_name='分类')),
                ('source', wagtail.core.fields.RichTextField(default='', verbose_name='出处')),
                ('usage', wagtail.core.fields.RichTextField(default='', verbose_name='用法')),
                ('function', wagtail.core.fields.RichTextField(default='', verbose_name='功用')),
                ('cures', wagtail.core.fields.RichTextField(default='', verbose_name='主治')),
                ('pathogenesis', wagtail.core.fields.RichTextField(default='', verbose_name='病机')),
                ('application', wagtail.core.fields.RichTextField(default='', verbose_name='运用')),
                ('indication', wagtail.core.fields.RichTextField(default='', verbose_name='方歌')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='prescriptioncomposition',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='main.PrescriptionPage'),
        ),
    ]
