# Generated by Django 2.2.8 on 2019-12-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_prescriptioncomposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptioncomposition',
            name='composition',
            field=models.TextField(default='', verbose_name='组成'),
        ),
    ]
