# Generated by Django 2.2.8 on 2019-12-13 09:06

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191213_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionpage',
            name='cures',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='主治'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='function',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='功用'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='usage',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='用法'),
        ),
    ]
