# Generated by Django 2.2.8 on 2019-12-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191213_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptioncomposition',
            name='composition',
        ),
        migrations.AddField(
            model_name='prescriptioncomposition',
            name='medicine_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.MedicinePage'),
        ),
    ]
