# Generated by Django 2.2.8 on 2019-12-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('main', '0008_auto_20191213_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='prescriptioncomposition',
            name='medicine_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.MedicinePage'),
        ),
    ]
