# Generated by Django 2.2.8 on 2019-12-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191213_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionpage',
            name='medicine_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.MedicinePage'),
        ),
    ]
