# Generated by Django 2.2.8 on 2019-12-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_prescriptionpage_medicine_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionpage',
            name='medicine_page',
        ),
    ]
