# Generated by Django 2.2.8 on 2019-12-18 08:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191218_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepage',
            name='category',
            field=models.TextField(default='', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='medicinepage',
            name='origin',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='medicinepage',
            name='production_region',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='产地'),
        ),
    ]
