# Generated by Django 2.2.8 on 2019-12-18 12:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191218_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepage',
            name='features',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='性状'),
        ),
        migrations.AddField(
            model_name='medicinepage',
            name='functions',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='功效'),
        ),
        migrations.AddField(
            model_name='medicinepage',
            name='properties',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='性味'),
        ),
        migrations.AddField(
            model_name='medicinepage',
            name='quality_requirements',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='品质'),
        ),
    ]
