# Generated by Django 2.2.8 on 2020-01-15 11:45

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191218_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionpage',
            name='application',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='运用'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='classification',
            field=models.TextField(default='', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='indication',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='方歌'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='pathogenesis',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='病机'),
        ),
        migrations.AddField(
            model_name='prescriptionpage',
            name='source',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='出处'),
        ),
    ]
